In [2]:
%matplotlib inline
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pymongo

In [3]:
index =["baseTopic" , "dst" , "src" , "seq" , "SNR" , "RSSIpkt" , "BW" , "CR" , "SF" , "sensor_id" , "version", "command_id", "data_length" , "data" , "mote_lon" , "mote_lat" , "time" ]
ltc_data = pd.read_csv('ltc_v1.0_100.csv',sep=',')
ltc_data.head()

,Unnamed: 0,baseTopic,dst,src,seq,SNR,RSSIpkt,BW,CR,SF,sensor_id,version,command_id,data_length,data,mote_lon,mote_lat,time
0,0,LTC-base1,1,7,3,7,-96,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:18:19
1,1,LTC-base1,1,7,0,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:00
2,2,LTC-base1,1,7,1,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:04
3,3,LTC-base1,1,7,2,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:24:58
4,4,LTC-base1,1,7,4,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:11

In [9]:
index1=["baseTopic" , "dst" , "src" , "seq" , "SNR" , "RSSIpkt" , "BW" , "CR" , "SF" , "sensor_id" , "version", "command_id", "data_length" , "data" , "mote_lon" , "mote_lat" , "time" ]
result_1 = pd.DataFrame(ltc_data,columns=index1)
result_1

,baseTopic,dst,src,seq,SNR,RSSIpkt,BW,CR,SF,sensor_id,version,command_id,data_length,data,mote_lon,mote_lat,time
0,LTC-base1,1,7,3,7,-96,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:18:19
1,LTC-base1,1,7,0,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:00
2,LTC-base1,1,7,1,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:04
3,LTC-base1,1,7,2,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:24:58
4,LTC-base1,1,7,4,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:11
5,LTC-base1,1,7,6,5,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:25
6,LTC-base1,1,7,7,6,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:33
7,LTC-base1,1,7,8,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:39
8,LTC-base1,1,7,9,8,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:45
9,LTC-base1,1,7,10,6,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:55
10,LTC-base1,1,7,11,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:59
11,LTC-base1,1,7,14,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:20
12,LTC-base1,1,7,15,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:25
13,LTC-base1,1,7,17,5,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:46
14,LTC-base1,1,7,18,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:53
15,LTC-base1,1,7,19,4,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:57
16,LTC-base1,1,7,20,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:00
17,LTC-base1,1,7,21,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:09
18,LTC-base1,1,7,23,4,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:17
19,LTC-base1,1,7,27,6,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:31
20,LTC-base1,1,7,30,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:40
21,LTC-base1,1,7,34,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:52
22,LTC-base1,1,7,35,5,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:00
23,LTC-base1,1,7,38,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:11
24,LTC-base1,1,7,40,6,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:18
25,LTC-base1,1,7,41,6,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:25
26,LTC-base1,1,7,45,8,-91,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:42
27,LTC-base1,1,7,46,8,-95,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:46
28,LTC-base1,1,7,47,8,-94,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:54
29,LTC-base1,1,7,48,8,-95,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,LTC-base1,1,7,108,-15,-61,125,4/5,12,226,2,5,77,�,0,0,2017-07-17 18:50:07
94,LTC-base1,1,7,10,6,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:13
95,LTC-base1,1,7,11,7,-98,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:16
96,LTC-base1,1,7,13,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:24
97,LTC-base1,1,7,16,5,-95,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:29
98,LTC-base1,1,7,17,6,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:32
99,LTC-base1,1,7,18,7,-93,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:34
100,LTC-base1,1,7,19,7,-83,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:38
101,LTC-base1,1,7,20,7,-93,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:41
102,LTC-base1,1,7,21,5,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:46
103,LTC-base1,1,7,22,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:48
104,LTC-base1,1,7,23,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:52
105,LTC-base1,1,7,24,5,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:55
106,LTC-base1,1,7,25,6,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:50:58
107,LTC-base1,1,7,26,8,-86,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:51:01
108,LTC-base1,1,7,27,8,-88,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:51:08
109,LTC-base1,1,2,16,8,-52,125,4/5,12,1,1,1,4,ping,0,0,2017-07-17 18:51:38
110,LTC-base1,1,7,44,1,-107,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:52:14
111,LTC-base1,1,7,63,-4,-48,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:53:33
112,LTC-base1,1,7,66,-2,-46,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:53:47
113,LTC-base1,1,7,70,6,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:54:10
114,LTC-base1,1,7,71,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:54:11
115,LTC-base1,1,7,72,-9,-55,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:54:19
116,LTC-base1,1,7,0,8,-27,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:56:03
117,LTC-base1,1,7,1,7,-60,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:56:09
118,LTC-base1,1,7,2,7,-31,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:56:11
119,LTC-base1,1,7,3,6,-33,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:56:17
120,LTC-base1,1,2,17,8,-64,125,4/5,12,1,1,1,4,ping,0,0,2017-07-17 19:00:54
121,LTC-base1,1,2,20,7,-62,125,4/5,12,1,1,1,4,ping,0,0,2017-07-17 19:03:58
122,LTC-base1,1,2,21,7,-61,125,4/5,12,1,1,1,4,ping,0,0,2017-07-17 19:04:10

In [4]:
# ltc_data.dtypes
# ltc_data['Unnamed: 0']=ltc_data['Unnamed: 0'].astype(np.int64)
# ltc_data['Unnamed: 0' > 1]
data1 = ltc_data[ltc_data['Unnamed: 0']> 0]
data2=data1[data1['Unnamed: 0']<61]
data2
data2['seq'].count()

,Unnamed: 0,baseTopic,dst,src,seq,SNR,RSSIpkt,BW,CR,SF,sensor_id,version,command_id,data_length,data,mote_lon,mote_lat,time
1,1,LTC-base1,1,7,0,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:00
2,2,LTC-base1,1,7,1,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:04
3,3,LTC-base1,1,7,2,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:24:58
4,4,LTC-base1,1,7,4,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:11
5,5,LTC-base1,1,7,6,5,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:25
6,6,LTC-base1,1,7,7,6,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:33
7,7,LTC-base1,1,7,8,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:39
8,8,LTC-base1,1,7,9,8,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:45
9,9,LTC-base1,1,7,10,6,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:55
10,10,LTC-base1,1,7,11,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:25:59
11,11,LTC-base1,1,7,14,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:20
12,12,LTC-base1,1,7,15,7,-99,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:25
13,13,LTC-base1,1,7,17,5,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:46
14,14,LTC-base1,1,7,18,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:53
15,15,LTC-base1,1,7,19,4,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:26:57
16,16,LTC-base1,1,7,20,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:00
17,17,LTC-base1,1,7,21,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:09
18,18,LTC-base1,1,7,23,4,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:17
19,19,LTC-base1,1,7,27,6,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:31
20,20,LTC-base1,1,7,30,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:40
21,21,LTC-base1,1,7,34,5,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:27:52
22,22,LTC-base1,1,7,35,5,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:00
23,23,LTC-base1,1,7,38,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:11
24,24,LTC-base1,1,7,40,6,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:18
25,25,LTC-base1,1,7,41,6,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:25
26,26,LTC-base1,1,7,45,8,-91,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:42
27,27,LTC-base1,1,7,46,8,-95,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:46
28,28,LTC-base1,1,7,47,8,-94,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:28:54
29,29,LTC-base1,1,7,48,8,-95,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:01
30,30,LTC-base1,1,7,49,7,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:17
31,31,LTC-base1,1,7,51,8,-92,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:39
32,32,LTC-base1,1,7,52,7,-92,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:43
33,33,LTC-base1,1,7,54,8,-88,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:29:56
34,34,LTC-base1,1,7,56,3,-105,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:30:47
35,35,LTC-base1,1,7,57,0,-108,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:30:53
36,36,LTC-base1,1,7,58,3,-104,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:01
37,37,LTC-base1,1,7,59,3,-105,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:05
38,38,LTC-base1,1,7,60,-2,-47,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:09
39,39,LTC-base1,1,7,61,-3,-48,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:17
40,40,LTC-base1,1,7,62,4,-104,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:21
41,41,LTC-base1,1,7,65,7,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:40
42,42,LTC-base1,1,7,66,6,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:44
43,43,LTC-base1,1,7,67,6,-98,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:47
44,44,LTC-base1,1,7,68,4,-104,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:50
45,45,LTC-base1,1,7,69,4,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:53
46,46,LTC-base1,1,7,70,7,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:31:57
47,47,LTC-base1,1,7,71,6,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:03
48,48,LTC-base1,1,7,74,7,-93,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:23
49,49,LTC-base1,1,7,75,7,-93,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:29
50,50,LTC-base1,1,7,76,9,-90,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:34
51,51,LTC-base1,1,7,77,9,-90,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:42
52,52,LTC-base1,1,7,79,8,-91,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:32:49
53,53,LTC-base1,1,7,82,8,-88,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:00
54,54,LTC-base1,1,7,83,9,-90,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:05
55,55,LTC-base1,1,7,84,7,-97,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:09
56,56,LTC-base1,1,7,85,9,-91,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:15
57,57,LTC-base1,1,7,86,8,-87,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:21
58,58,LTC-base1,1,7,87,8,-89,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:25
59,59,LTC-base1,1,7,88,8,-93,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:31
60,60,LTC-base1,1,7,90,8,-87,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:33:42

In [5]:
rec_count=data2['seq'].count()
all_count=data2['seq'].max()+1
# miss_pack = data2['seq'].count()/data2['seq'].max()
miss_pack=(rec_count/all_count)*100
# rec_count
# all_count
miss_pack

60

In [7]:
data1 = ltc_data[ltc_data['Unnamed: 0']> 0]
data2=data1[data1['Unnamed: 0']<61]
rec_count=data2['seq'].count()
all_count=data2['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

65.934065934065927

In [93]:
data_seq= ltc_data[ltc_data['seq']==0]   #判断初始化位置
data_seq

,Unnamed: 0,baseTopic,dst,src,seq,SNR,RSSIpkt,BW,CR,SF,sensor_id,version,command_id,data_length,data,mote_lon,mote_lat,time
1,1,LTC-base1,1,7,0,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:20:00
61,61,LTC-base1,1,7,0,8,-87,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:34:04
68,68,LTC-base1,1,7,0,7,-101,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:41:26
72,72,LTC-base1,1,7,0,2,-107,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:42:36
73,73,LTC-base1,1,7,0,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:42:54
76,76,LTC-base1,1,7,0,6,-102,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:44:10
78,78,LTC-base1,1,7,0,5,-103,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:45:10
84,84,LTC-base1,1,7,0,7,-100,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:47:41
88,88,LTC-base1,1,7,0,3,-105,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:49:48
116,116,LTC-base1,1,7,0,8,-27,125,4/5,12,2,1,9,1,",",0,0,2017-07-17 18:56:03

In [9]:
data3 = ltc_data[ltc_data['Unnamed: 0']> 60]
data4=data3[data3['Unnamed: 0']<68]
rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

100.0

In [10]:
data3 = ltc_data[ltc_data['Unnamed: 0']> 69]
data4=data3[data3['Unnamed: 0']<72]
rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

22.222222222222221

In [11]:
data3 = ltc_data[ltc_data['Unnamed: 0']> 72]
data4=data3[data3['Unnamed: 0']<76]

rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

33.333333333333329

In [12]:
data3 = ltc_data[ltc_data['Unnamed: 0']> 83]
data4=data3[data3['Unnamed: 0']<88]

rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

26.666666666666668

In [13]:
# 存在异常值
data3 = ltc_data[ltc_data['Unnamed: 0']> 87]
data4=data3[data3['Unnamed: 0']<116]

rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

25.688073394495415

In [14]:

data3 = ltc_data[ltc_data['Unnamed: 0']> 115]
data4=data3[data3['Unnamed: 0']<124]

rec_count=data4['seq'].count()
all_count=data4['seq'].max()+1
miss_pack=(rec_count/all_count)*100
miss_pack

31.818181818181817