In [1]:
%matplotlib inline
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
result = pd.read_csv('ltc_v1.0_Data_7_25_5.csv',sep=',')
result.head()

,id,collcetion_latest_id,base_topic,dst,src,seq,SNR,RSSIpkt,BW,CR,SF,sensor_id,version,command_id,data_length,data,mote_lon,mote_lat,time,distance2base
0,1,39,LTC-base1,1,2,2,8,-86,125,4/5,12,2,1,9,1,",",0.0,0.0,2017/7/25 8:14,12200000.0
1,2,39,LTC-base1,1,2,4,8,-84,125,4/5,12,2,1,9,1,",",0.0,0.0,2017/7/25 8:14,12200000.0
2,3,39,LTC-base1,1,2,7,8,-90,125,4/5,12,2,1,9,1,",",0.0,0.0,2017/7/25 8:14,12200000.0
3,4,39,LTC-base1,1,2,0,8,-91,125,4/5,12,2,1,9,1,",",0.0,0.0,2017/7/25 8:14,12200000.0
4,5,39,LTC-base1,1,2,1,7,-88,125,4/5,12,2,1,9,1,",",0.0,0.0,2017/7/25 8:14,12200000.0

In [3]:
address6_1=result[result['id']>327]
address6=address6_1[address6_1['id']<410]
address6.count()

id                      82
collcetion_latest_id    82
base_topic              82
dst                     82
src                     82
seq                     82
SNR                     82
RSSIpkt                 82
BW                      82
CR                      82
SF                      82
sensor_id               82
version                 82
command_id              82
data_length             82
data                    82
mote_lon                82
mote_lat                82
time                    82
distance2base           82
dtype: int64

In [35]:
index_1=["id","collcetion_latest_id","base_topic" ,"dst" ,"src","seq" ,"SNR" , "RSSIpkt" ,"sensor_id",  "data_length" ,'mote_lon','mote_lat', "time" , "distance2base"]
columns=index_1
address6_data = pd.DataFrame(address6,columns=index_1)
address6_data.count()

id                      82
collcetion_latest_id    82
base_topic              82
dst                     82
src                     82
seq                     82
SNR                     82
RSSIpkt                 82
sensor_id               82
data_length             82
mote_lon                82
mote_lat                82
time                    82
distance2base           82
dtype: int64

In [6]:
address6_data1 = pd.DataFrame((x.split(' ') for x in address6_data.time),index=address6_data.index,columns=['yyyy/MM/d','time'])

In [43]:
YY = pd.DataFrame(address6_data1['yyyy/MM/d'])
YY.count()

yyyy/MM/d    82
dtype: int64

In [45]:
address6_data2 = pd.merge(address6_data,YY,left_index=True,right_index=True,how='outer')
address6_data2.count()

id                      82
collcetion_latest_id    82
base_topic              82
dst                     82
src                     82
seq                     82
SNR                     82
RSSIpkt                 82
sensor_id               82
data_length             82
mote_lon                82
mote_lat                82
time                    82
distance2base           82
yyyy/MM/d               82
dtype: int64

In [46]:
HH = pd.DataFrame(address6_data1['time'])
# HH['base_topic']='LTC-base1'
HH

     time
327  9:00
328  9:00
329  9:00
330  9:00
331  9:00
332  9:00
333  9:00
334  9:00
335  9:00
336  9:00
337  9:00
338  9:00
339  9:00
340  9:00
341  9:00
342  9:00
343  9:00
344  9:01
345  9:01
346  9:01
347  9:01
348  9:01
349  9:01
350  9:01
351  9:01
352  9:01
353  9:01
354  9:01
355  9:01
356  9:02
..    ...
379  9:04
380  9:04
381  9:04
382  9:04
383  9:04
384  9:05
385  9:05
386  9:05
387  9:05
388  9:05
389  9:05
390  9:05
391  9:05
392  9:05
393  9:05
394  9:06
395  9:06
396  9:13
397  9:13
398  9:13
399  9:13
400  9:13
401  9:13
402  9:13
403  9:14
404  9:14
405  9:14
406  9:14
407  9:14
408  9:14

[82 rows x 1 columns]

In [47]:
address6_data3 = pd.DataFrame((x.split(':') for x in HH .time),index=HH .index,columns=['HH','mm'])

In [48]:
# address6_data3_h = address6_data3['HH'].astype(int)+8

In [49]:
# address6_data3_h1 = pd.DataFrame(address6_data3_h)
# address6_data3_h1['base_topic']='LTC-base1'
# address6_data3_h1.count()

In [50]:
# # address6_data3_h1
# address6_data4 = pd.merge(address6_data2,address6_data3_h1)
# address6_data4

In [51]:
address6_data3_m = pd.DataFrame(address6_data3['mm'])
address6_data3_m['base_topic']='LTC-base1'
# address6_data3['mm']
# address6_data3_m.head()
# address6_data3_m.count()
address6_data2.count()

id                      82
collcetion_latest_id    82
base_topic              82
dst                     82
src                     82
seq                     82
SNR                     82
RSSIpkt                 82
sensor_id               82
data_length             82
mote_lon                82
mote_lat                82
time                    82
distance2base           82
yyyy/MM/d               82
dtype: int64

In [53]:
address6_data5 = pd.merge(address6_data2,address6_data3_m,left_index=True,right_index=True,how='outer')
address6_data5.count()
address6_data5['HH']='17'
address6_data5

,id,collcetion_latest_id,base_topic_x,dst,src,seq,SNR,RSSIpkt,sensor_id,data_length,mote_lon,mote_lat,time,distance2base,yyyy/MM/d,mm,base_topic_y,HH
327,328,39,LTC-base1,1,2,1,8,-90,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
328,329,39,LTC-base1,1,2,2,8,-94,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
329,330,39,LTC-base1,1,2,3,8,-93,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
330,331,39,LTC-base1,1,2,4,8,-95,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
331,332,39,LTC-base1,1,2,5,8,-93,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
332,333,39,LTC-base1,1,2,6,9,-92,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
333,334,39,LTC-base1,1,2,7,8,-93,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
334,335,39,LTC-base1,1,2,8,7,-98,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
335,336,39,LTC-base1,1,2,9,8,-98,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
336,337,39,LTC-base1,1,2,0,7,-94,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
337,338,39,LTC-base1,1,2,1,8,-96,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
338,339,39,LTC-base1,1,2,2,8,-97,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
339,340,39,LTC-base1,1,2,3,8,-97,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
340,341,39,LTC-base1,1,2,4,8,-97,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
341,342,39,LTC-base1,1,2,5,8,-96,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
342,343,39,LTC-base1,1,2,7,8,-92,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
343,344,39,LTC-base1,1,2,8,8,-93,2,1,0.000000,0.000000,2017/7/25 9:00,12200000.0,2017/7/25,00,LTC-base1,17
344,345,39,LTC-base1,1,2,9,7,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
345,346,39,LTC-base1,1,2,0,8,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
346,347,39,LTC-base1,1,2,1,9,-92,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
347,348,39,LTC-base1,1,2,2,8,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
348,349,39,LTC-base1,1,2,3,9,-93,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
349,350,39,LTC-base1,1,2,4,8,-91,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
350,351,39,LTC-base1,1,2,5,8,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
351,352,39,LTC-base1,1,2,6,8,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
352,353,39,LTC-base1,1,2,7,8,-94,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
353,354,39,LTC-base1,1,2,8,8,-96,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
354,355,39,LTC-base1,1,2,9,9,-96,2,1,0.000000,0.000000,2017/7/25 9:01,12200000.0,2017/7/25,01,LTC-base1,17
355,356,38,LTC-base1,1,3,0,7,-86,2,20,114.500163,36.571268,2017/7/25 9:01,1332.0,2017/7/25,01,LTC-base1,17
356,357,38,LTC-base1,1,3,1,8,-91,2,20,114.500162,36.571283,2017/7/25 9:02,1331.0,2017/7/25,02,LTC-base1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,380,38,LTC-base1,1,3,9,9,-94,2,20,114.500115,36.571244,2017/7/25 9:04,1337.0,2017/7/25,04,LTC-base1,17
380,381,37,LTC-base1,1,4,0,8,-90,2,20,114.500143,36.571265,2017/7/25 9:04,1333.0,2017/7/25,04,LTC-base1,17
381,382,37,LTC-base1,1,4,1,8,-93,2,20,114.500126,36.571263,2017/7/25 9:04,1335.0,2017/7/25,04,LTC-base1,17
382,383,37,LTC-base1,1,4,2,7,-96,2,20,114.500105,36.571242,2017/7/25 9:04,1338.0,2017/7/25,04,LTC-base1,17
383,384,37,LTC-base1,1,4,3,6,-109,2,20,114.500083,36.571260,2017/7/25 9:04,1338.0,2017/7/25,04,LTC-base1,17
384,385,37,LTC-base1,1,4,4,8,-92,2,20,114.500079,36.571251,2017/7/25 9:05,1339.0,2017/7/25,05,LTC-base1,17
385,386,37,LTC-base1,1,4,5,9,-88,2,20,114.500107,36.571263,2017/7/25 9:05,1336.0,2017/7/25,05,LTC-base1,17
386,387,37,LTC-base1,1,4,6,10,-87,2,20,114.500121,36.571264,2017/7/25 9:05,1335.0,2017/7/25,05,LTC-base1,17
387,388,37,LTC-base1,1,4,7,9,-87,2,20,114.500140,36.571261,2017/7/25 9:05,1334.0,2017/7/25,05,LTC-base1,17
388,389,37,LTC-base1,1,4,8,9,-87,2,20,114.500157,36.571254,2017/7/25 9:05,1333.0,2017/7/25,05,LTC-base1,17
389,390,37,LTC-base1,1,4,9,9,-88,2,20,114.500164,36.571243,2017/7/25 9:05,1333.0,2017/7/25,05,LTC-base1,17
390,391,37,LTC-base1,1,4,0,10,-89,2,20,114.500168,36.571259,2017/7/25 9:05,1332.0,2017/7/25,05,LTC-base1,17
391,392,37,LTC-base1,1,4,1,9,-88,2,20,114.500183,36.571277,2017/7/25 9:05,1330.0,2017/7/25,05,LTC-base1,17
392,393,37,LTC-base1,1,4,2,10,-88,2,20,114.500189,36.571277,2017/7/25 9:05,1329.0,2017/7/25,05,LTC-base1,17
393,394,37,LTC-base1,1,4,3,9,-89,2,20,114.500184,36.571294,2017/7/25 9:05,1329.0,2017/7/25,05,LTC-base1,17
394,395,37,LTC-base1,1,4,6,-13,-43,2,20,114.500199,36.571308,2017/7/25 9:06,1327.0,2017/7/25,06,LTC-base1,17
395,396,37,LTC-base1,1,4,7,-15,-46,2,20,114.500198,36.571325,2017/7/25 9:06,1326.0,2017/7/25,06,LTC-base1,17
396,397,37,LTC-base1,1,4,6,8,-79,2,20,114.501397,36.571121,2017/7/25 9:13,1239.0,2017/7/25,13,LTC-base1,17
397,398,37,LTC-base1,1,4,8,7,-81,2,20,114.501403,36.571155,2017/7/25 9:13,1237.0,2017/7/25,13,LTC-base1,17
398,399,37,LTC-base1,1,4,9,7,-80,2,20,114.501388,36.571182,2017/7/25 9:13,1237.0,2017/7/25,13,LTC-base1,17
399,400,37,LTC-base1,1,4,0,9,-81,2,20,114.501381,36.571184,2017/7/25 9:13,1238.0,2017/7/25,13,LTC-base1,17
400,401,37,LTC-base1,1,4,1,8,-82,2,20,114.501345,36.571303,2017/7/25 9:13,1234.0,2017/7/25,13,LTC-base1,17
401,402,37,LTC-base1,1,4,2,9,-81,2,20,114.501328,36.571383,2017/7/25 9:13,1232.0,2017/7/25,13,LTC-base1,17
402,403,37,LTC-base1,1,4,3,7,-85,2,20,114.501330,36.571392,2017/7/25 9:13,1231.0,2017/7/25,13,LTC-base1,17
403,404,37,LTC-base1,1,4,4,8,-90,2,20,114.501299,36.571417,2017/7/25 9:14,1233.0,2017/7/25,14,LTC-base1,17
404,405,37,LTC-base1,1,4,5,10,-87,2,20,114.501297,36.571408,2017/7/25 9:14,1233.0,2017/7/25,14,LTC-base1,17
405,406,37,LTC-base1,1,4,6,8,-84,2,20,114.501280,36.571443,2017/7/25 9:14,1233.0,2017/7/25,14,LTC-base1,17
406,407,37,LTC-base1,1,4,7,8,-98,2,20,114.501267,36.571491,2017/7/25 9:14,1232.0,2017/7/25,14,LTC-base1,17
407,408,37,LTC-base1,1,4,8,8,-92,2,20,114.501259,36.571547,2017/7/25 9:14,1230.0,2017/7/25,14,LTC-base1,17
408,409,37,LTC-base1,1,4,9,9,-90,2,20,114.501226,36.571598,2017/7/25 9:14,1230.0,2017/7/25,14,LTC-base1,17

In [58]:
index_1=["id","collcetion_latest_id","dst" ,"src","seq" ,"SNR" , "RSSIpkt" ,  "data_length" ,'mote_lon','mote_lat', 'time','yyyy/MM/d' ,'HH','mm',"distance2base"]
columns=index_1
address6_data = pd.DataFrame(address6_data5,columns=index_1)
address6_data

,id,collcetion_latest_id,dst,src,seq,SNR,RSSIpkt,data_length,mote_lon,mote_lat,time,yyyy/MM/d,HH,mm,distance2base
327,328,39,1,2,1,8,-90,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
328,329,39,1,2,2,8,-94,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
329,330,39,1,2,3,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
330,331,39,1,2,4,8,-95,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
331,332,39,1,2,5,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
332,333,39,1,2,6,9,-92,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
333,334,39,1,2,7,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
334,335,39,1,2,8,7,-98,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
335,336,39,1,2,9,8,-98,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
336,337,39,1,2,0,7,-94,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
337,338,39,1,2,1,8,-96,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
338,339,39,1,2,2,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
339,340,39,1,2,3,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
340,341,39,1,2,4,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
341,342,39,1,2,5,8,-96,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
342,343,39,1,2,7,8,-92,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
343,344,39,1,2,8,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
344,345,39,1,2,9,7,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
345,346,39,1,2,0,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
346,347,39,1,2,1,9,-92,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
347,348,39,1,2,2,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
348,349,39,1,2,3,9,-93,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
349,350,39,1,2,4,8,-91,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
350,351,39,1,2,5,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
351,352,39,1,2,6,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
352,353,39,1,2,7,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
353,354,39,1,2,8,8,-96,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
354,355,39,1,2,9,9,-96,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
355,356,38,1,3,0,7,-86,20,114.500163,36.571268,2017/7/25 9:01,2017/7/25,17,01,1332.0
356,357,38,1,3,1,8,-91,20,114.500162,36.571283,2017/7/25 9:02,2017/7/25,17,02,1331.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,380,38,1,3,9,9,-94,20,114.500115,36.571244,2017/7/25 9:04,2017/7/25,17,04,1337.0
380,381,37,1,4,0,8,-90,20,114.500143,36.571265,2017/7/25 9:04,2017/7/25,17,04,1333.0
381,382,37,1,4,1,8,-93,20,114.500126,36.571263,2017/7/25 9:04,2017/7/25,17,04,1335.0
382,383,37,1,4,2,7,-96,20,114.500105,36.571242,2017/7/25 9:04,2017/7/25,17,04,1338.0
383,384,37,1,4,3,6,-109,20,114.500083,36.571260,2017/7/25 9:04,2017/7/25,17,04,1338.0
384,385,37,1,4,4,8,-92,20,114.500079,36.571251,2017/7/25 9:05,2017/7/25,17,05,1339.0
385,386,37,1,4,5,9,-88,20,114.500107,36.571263,2017/7/25 9:05,2017/7/25,17,05,1336.0
386,387,37,1,4,6,10,-87,20,114.500121,36.571264,2017/7/25 9:05,2017/7/25,17,05,1335.0
387,388,37,1,4,7,9,-87,20,114.500140,36.571261,2017/7/25 9:05,2017/7/25,17,05,1334.0
388,389,37,1,4,8,9,-87,20,114.500157,36.571254,2017/7/25 9:05,2017/7/25,17,05,1333.0
389,390,37,1,4,9,9,-88,20,114.500164,36.571243,2017/7/25 9:05,2017/7/25,17,05,1333.0
390,391,37,1,4,0,10,-89,20,114.500168,36.571259,2017/7/25 9:05,2017/7/25,17,05,1332.0
391,392,37,1,4,1,9,-88,20,114.500183,36.571277,2017/7/25 9:05,2017/7/25,17,05,1330.0
392,393,37,1,4,2,10,-88,20,114.500189,36.571277,2017/7/25 9:05,2017/7/25,17,05,1329.0
393,394,37,1,4,3,9,-89,20,114.500184,36.571294,2017/7/25 9:05,2017/7/25,17,05,1329.0
394,395,37,1,4,6,-13,-43,20,114.500199,36.571308,2017/7/25 9:06,2017/7/25,17,06,1327.0
395,396,37,1,4,7,-15,-46,20,114.500198,36.571325,2017/7/25 9:06,2017/7/25,17,06,1326.0
396,397,37,1,4,6,8,-79,20,114.501397,36.571121,2017/7/25 9:13,2017/7/25,17,13,1239.0
397,398,37,1,4,8,7,-81,20,114.501403,36.571155,2017/7/25 9:13,2017/7/25,17,13,1237.0
398,399,37,1,4,9,7,-80,20,114.501388,36.571182,2017/7/25 9:13,2017/7/25,17,13,1237.0
399,400,37,1,4,0,9,-81,20,114.501381,36.571184,2017/7/25 9:13,2017/7/25,17,13,1238.0
400,401,37,1,4,1,8,-82,20,114.501345,36.571303,2017/7/25 9:13,2017/7/25,17,13,1234.0
401,402,37,1,4,2,9,-81,20,114.501328,36.571383,2017/7/25 9:13,2017/7/25,17,13,1232.0
402,403,37,1,4,3,7,-85,20,114.501330,36.571392,2017/7/25 9:13,2017/7/25,17,13,1231.0
403,404,37,1,4,4,8,-90,20,114.501299,36.571417,2017/7/25 9:14,2017/7/25,17,14,1233.0
404,405,37,1,4,5,10,-87,20,114.501297,36.571408,2017/7/25 9:14,2017/7/25,17,14,1233.0
405,406,37,1,4,6,8,-84,20,114.501280,36.571443,2017/7/25 9:14,2017/7/25,17,14,1233.0
406,407,37,1,4,7,8,-98,20,114.501267,36.571491,2017/7/25 9:14,2017/7/25,17,14,1232.0
407,408,37,1,4,8,8,-92,20,114.501259,36.571547,2017/7/25 9:14,2017/7/25,17,14,1230.0
408,409,37,1,4,9,9,-90,20,114.501226,36.571598,2017/7/25 9:14,2017/7/25,17,14,1230.0

In [70]:
address6_data[]

MemoryError:

,id,collcetion_latest_id,dst,src,seq,SNR,RSSIpkt,data_length,mote_lon,mote_lat,time,yyyy/MM/d,HH,mm,distance2base
327,328,39,1,2,1,8,-90,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
328,329,39,1,2,2,8,-94,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
329,330,39,1,2,3,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
330,331,39,1,2,4,8,-95,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
331,332,39,1,2,5,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
332,333,39,1,2,6,9,-92,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
333,334,39,1,2,7,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
334,335,39,1,2,8,7,-98,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
335,336,39,1,2,9,8,-98,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
336,337,39,1,2,0,7,-94,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
337,338,39,1,2,1,8,-96,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
338,339,39,1,2,2,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
339,340,39,1,2,3,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
340,341,39,1,2,4,8,-97,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
341,342,39,1,2,5,8,-96,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
342,343,39,1,2,7,8,-92,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
343,344,39,1,2,8,8,-93,1,0.000000,0.000000,2017/7/25 9:00,2017/7/25,17,00,12200000.0
344,345,39,1,2,9,7,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
345,346,39,1,2,0,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
346,347,39,1,2,1,9,-92,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
347,348,39,1,2,2,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
348,349,39,1,2,3,9,-93,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
349,350,39,1,2,4,8,-91,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
350,351,39,1,2,5,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
351,352,39,1,2,6,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
352,353,39,1,2,7,8,-94,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
353,354,39,1,2,8,8,-96,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
354,355,39,1,2,9,9,-96,1,0.000000,0.000000,2017/7/25 9:01,2017/7/25,17,01,12200000.0
355,356,38,1,3,0,7,-86,20,114.500163,36.571268,2017/7/25 9:01,2017/7/25,17,01,1332.0
356,357,38,1,3,1,8,-91,20,114.500162,36.571283,2017/7/25 9:02,2017/7/25,17,02,1331.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,380,38,1,3,9,9,-94,20,114.500115,36.571244,2017/7/25 9:04,2017/7/25,17,04,1337.0
380,381,37,1,4,0,8,-90,20,114.500143,36.571265,2017/7/25 9:04,2017/7/25,17,04,1333.0
381,382,37,1,4,1,8,-93,20,114.500126,36.571263,2017/7/25 9:04,2017/7/25,17,04,1335.0
382,383,37,1,4,2,7,-96,20,114.500105,36.571242,2017/7/25 9:04,2017/7/25,17,04,1338.0
383,384,37,1,4,3,6,-109,20,114.500083,36.571260,2017/7/25 9:04,2017/7/25,17,04,1338.0
384,385,37,1,4,4,8,-92,20,114.500079,36.571251,2017/7/25 9:05,2017/7/25,17,05,1339.0
385,386,37,1,4,5,9,-88,20,114.500107,36.571263,2017/7/25 9:05,2017/7/25,17,05,1336.0
386,387,37,1,4,6,10,-87,20,114.500121,36.571264,2017/7/25 9:05,2017/7/25,17,05,1335.0
387,388,37,1,4,7,9,-87,20,114.500140,36.571261,2017/7/25 9:05,2017/7/25,17,05,1334.0
388,389,37,1,4,8,9,-87,20,114.500157,36.571254,2017/7/25 9:05,2017/7/25,17,05,1333.0
389,390,37,1,4,9,9,-88,20,114.500164,36.571243,2017/7/25 9:05,2017/7/25,17,05,1333.0
390,391,37,1,4,0,10,-89,20,114.500168,36.571259,2017/7/25 9:05,2017/7/25,17,05,1332.0
391,392,37,1,4,1,9,-88,20,114.500183,36.571277,2017/7/25 9:05,2017/7/25,17,05,1330.0
392,393,37,1,4,2,10,-88,20,114.500189,36.571277,2017/7/25 9:05,2017/7/25,17,05,1329.0
393,394,37,1,4,3,9,-89,20,114.500184,36.571294,2017/7/25 9:05,2017/7/25,17,05,1329.0
394,395,37,1,4,6,-13,-43,20,114.500199,36.571308,2017/7/25 9:06,2017/7/25,17,06,1327.0
395,396,37,1,4,7,-15,-46,20,114.500198,36.571325,2017/7/25 9:06,2017/7/25,17,06,1326.0
396,397,37,1,4,6,8,-79,20,114.501397,36.571121,2017/7/25 9:13,2017/7/25,17,13,1239.0
397,398,37,1,4,8,7,-81,20,114.501403,36.571155,2017/7/25 9:13,2017/7/25,17,13,1237.0
398,399,37,1,4,9,7,-80,20,114.501388,36.571182,2017/7/25 9:13,2017/7/25,17,13,1237.0
399,400,37,1,4,0,9,-81,20,114.501381,36.571184,2017/7/25 9:13,2017/7/25,17,13,1238.0
400,401,37,1,4,1,8,-82,20,114.501345,36.571303,2017/7/25 9:13,2017/7/25,17,13,1234.0
401,402,37,1,4,2,9,-81,20,114.501328,36.571383,2017/7/25 9:13,2017/7/25,17,13,1232.0
402,403,37,1,4,3,7,-85,20,114.501330,36.571392,2017/7/25 9:13,2017/7/25,17,13,1231.0
403,404,37,1,4,4,8,-90,20,114.501299,36.571417,2017/7/25 9:14,2017/7/25,17,14,1233.0
404,405,37,1,4,5,10,-87,20,114.501297,36.571408,2017/7/25 9:14,2017/7/25,17,14,1233.0
405,406,37,1,4,6,8,-84,20,114.501280,36.571443,2017/7/25 9:14,2017/7/25,17,14,1233.0
406,407,37,1,4,7,8,-98,20,114.501267,36.571491,2017/7/25 9:14,2017/7/25,17,14,1232.0
407,408,37,1,4,8,8,-92,20,114.501259,36.571547,2017/7/25 9:14,2017/7/25,17,14,1230.0
408,409,37,1,4,9,9,-90,20,114.501226,36.571598,2017/7/25 9:14,2017/7/25,17,14,1230.0